dist: bionic
os: linux
language: generic
env:
  global:
    - PATH=/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH
before_install:
  - wget https://github.com/nxadm/rakudo-pkg/releases/download/v2019.07.1/rakudo-pkg-Ubuntu18.04_2019.07.1-01_amd64.deb
  - sudo dpkg -i rakudo-pkg-Ubuntu18.04_2019.07.1-01_amd64.deb
  - sudo apt-get -qq update
  - sudo apt-get install libqrencode3
install:
  - zef install --deps-only --/test .
script:
  - PERL6_QRENCODE_LIB=libqrencode.so.3 PERL6LIB=$PWD/lib prove -e perl6 -vr t/
